export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const UPDATE_INFO_CUSTOMMER_REQUEST = "UPDATE_INFO_CUSTOMMER_REQUEST";
export const UPDATE_INFO_CUSTOMMER_SUCCESS = "UPDATE_INFO_CUSTOMMER_SUCCESS";
export const UPDATE_INFO_CUSTOMMER_ERROR = "UPDATE_INFO_CUSTOMMER_ERROR";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_ERROR = "UPDATE_AVATAR_ERROR";

export const GET_ORDER_BY_CUSOMER_REQUEST = "GET_ORDER_BY_CUSOMER_REQUEST";
export const GET_ORDER_BY_CUSOMER_SUCCESS = "GET_ORDER_BY_CUSOMER_SUCCESS";
export const GET_ORDER_BY_CUSOMER_ERROR = "GET_ORDER_BY_CUSOMER_ERROR";

export const LOGIN_GOOGLE_REQUEST = "LOGIN_GOOGLE_REQUEST";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_ERROR = "LOGIN_GOOGLE_ERROR";

export const LOGIN_FACEBOOK_REQUEST = "LOGIN_FACEBOOK_REQUEST";
export const LOGIN_FACEBOOK_SUCCESS = "LOGIN_FACEBOOK_SUCCESS";
export const LOGIN_FACEBOOK_ERROR = "LOGIN_FACEBOOK_ERROR";