export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_CART_BY_SIGNIN = "ADD_CART_BY_SIGNIN";
export const PLUS_QTY_PRODUCT_IN_CART = "PLUS_QTY_PRODUCT_IN_CART";
export const MINUS_QTY_PRODUCT_IN_CART = "MINUS_QTY_PRODUCT_IN_CART";
