export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR";


export const GET_PRODUCT_BY_CATEGORY_REQUEST = "GET_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_ERROR = "GET_PRODUCT_BY_CATEGORY_ERROR";

export const GET_PRODUCT_BY_SORT_REQUEST = "GET_PRODUCT_BY_SORT_REQUEST";
export const GET_PRODUCT_BY_SORT_SUCCESS = "GET_PRODUCT_BY_SORT_SUCCESS";
export const GET_PRODUCT_BY_SORT_ERROR = "GET_PRODUCT_BY_SORT_ERROR";

export const GET_PRODUCT_BY_PRICE_REQUEST = "GET_PRODUCT_BY_PRICE_REQUEST";
export const GET_PRODUCT_BY_PRICE_SUCCESS = "GET_PRODUCT_BY_PRICE_SUCCESS";
export const GET_PRODUCT_BY_PRICE_ERROR = "GET_PRODUCT_BY_PRICE_ERROR";

export const GET_PRODUCT_BY_SIZE_REQUEST = "GET_PRODUCT_BY_SIZE_REQUEST";
export const GET_PRODUCT_BY_SIZE_SUCCESS = "GET_PRODUCT_BY_SIZE_SUCCESS";
export const GET_PRODUCT_BY_SIZE_ERROR = "GET_PRODUCT_BY_SIZE_ERROR";

export const GET_DETAIL_PRODUCT_REQUEST = "GET_DETAIL_PRODUCT_REQUEST";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_ERROR = "GET_DETAIL_PRODUCT_ERROR";

export const GET_RELATE_PRODUCT_REQUEST = "GET_RELATE_PRODUCT_REQUEST";
export const GET_RELATE_PRODUCT_SUCCESS = "GET_RELATE_PRODUCT_SUCCESS";
export const GET_RELATE_PRODUCT_ERROR = "GET_RELATE_PRODUCT_ERROR";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_ERROR = "SEARCH_PRODUCT_ERROR";

export const POST_REVIEW_PRODUCT_REQUEST = "POST_REVIEW_PRODUCT_REQUEST";
export const POST_REVIEW_PRODUCT_SUCCESS = "POST_REVIEW_PRODUCT_SUCCESS";
export const POST_REVIEW_PRODUCT_ERROR = "POST_REVIEW_PRODUCT_ERROR";

export const UPDATE_REVIEW_PRODUCT_SUCCESS = "UPDATE_REVIEW_PRODUCT_SUCCESS";

export const GET_PRODUCT_HOME_REQUEST = "GET_PRODUCT_HOME_REQUEST";
export const GET_PRODUCT_HOME_SUCCESS = "GET_PRODUCT_HOME_SUCCESS";
export const GET_PRODUCT_HOME_ERROR = "GET_PRODUCT_HOME_ERROR";