export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_ERROR = "ADMIN_SIGNIN_ERROR";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_GET_ACCOUNT_REQUEST = "ADMIN_GET_ACCOUNT_REQUEST";
export const ADMIN_GET_ACCOUNT_SUCCESS = "ADMIN_GET_ACCOUNT_SUCCESS";
export const ADMIN_GET_ACCOUNT_ERROR = "ADMIN_GET_ACCOUNT_ERROR";

export const ADMIN_GET_ACCOUNT_NEW_REQUEST = "ADMIN_GET_ACCOUNT_NEW_REQUEST";
export const ADMIN_GET_ACCOUNT_NEW_SUCCESS = "ADMIN_GET_ACCOUNT_NEW_SUCCESS";
export const ADMIN_GET_ACCOUNT_NEW_ERROR = "ADMIN_GET_ACCOUNT_NEW_ERROR";

export const ADMIN_GET_CART_REQUEST = "ADMIN_GET_CART_REQUEST";
export const ADMIN_GET_CART_SUCCESS = "ADMIN_GET_CART_SUCCESS";
export const ADMIN_GET_CART_ERROR = "ADMIN_GET_CART_ERROR";

export const UPDATE_ACCOUNT_ADMIN_REQUEST = "UPDATE_ACCOUNT_ADMIN_REQUEST";
export const UPDATE_ACCOUNT_ADMIN_SUCCESS = "UPDATE_ACCOUNT_ADMIN_SUCCESS";
export const UPDATE_ACCOUNT_ADMIN_ERROR = "UPDATE_ACCOUNT_ADMIN_ERROR";

export const ADMIN_REGESTER_ACCOUNT_REQUEST = "ADMIN_REGESTER_ACCOUNT_REQUEST";
export const ADMIN_REGESTER_ACCOUNT_SUCCESS = "ADMIN_REGESTER_ACCOUNT_SUCCESS";
export const ADMIN_REGESTER_ACCOUNT_ERROR = "ADMIN_REGESTER_ACCOUNT_ERROR";