export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_ERROR = "GET_ALL_ORDER_ERROR";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";


export const ORDER_THE_HOME_REQUEST = "ORDER_THE_HOME_REQUEST";
export const ORDER_THE_HOME_SUCCESS = "ORDER_THE_HOME_SUCCESS";
export const ORDER_THE_HOME_ERROR = "ORDER_THE_HOME_ERROR";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_ERROR = "DELETE_RDER_ERROR";