export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR";

export const GET_ALL_REVIEW_REQUEST = "GET_ALL_REVIEW_REQUEST";
export const GET_ALL_REVIEW_SUCCESS = "GET_ALL_REVIEW_SUCCESS";
export const GET_ALL_REVIEW_ERROR = "GET_ALL_REVIEW_ERROR";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_ERROR = "DELETE_REVIEW_ERROR";